version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpassword"
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db

volumes:
  mysql:
